# Solarized Light palette:
#   base3=#fdf6e3   base2=#eee8d5   base1=#93a1a1   base0=#839496
#   base00=#657b83  base01=#586e75  blue=#268bd2    cyan=#2aa198

set -g status-style "bg=#eee8d5,fg=#657b83"
set -g message-style "bg=#eee8d5,fg=#2aa198"
set -g pane-border-style "fg=#93a1a1"
set -g pane-active-border-style "fg=#268bd2"
set -g status-left "#[fg=#268bd2,bold]#S #[fg=#93a1a1,nobold]| #[fg=#657b83]#(whoami)@#H"
set -g status-right "#[fg=#93a1a1]%Y-%m-%d #[fg=#657b83]%H:%M"
