task :default => ['vim:update', 'vim:link']

namespace "vim" do
  desc "Setup Vim submodules"
  task :update do
    system "git submodule sync > /dev/null"
    system "git submodule update --init"
  end

  desc %(Make ~/.vimrc and ~/.gvimrc symlinks)
  task :link do
    %w[vimrc gvimrc].each do |script|
      dotfile = File.join(ENV['HOME'], ".#{script}")
      if File.exist? dotfile
        warn "~/.#{script} already exists"
      else
        ln_s File.join('.vim', script), dotfile
      end
    end
  end

end
